using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace smss_api_db_layer.entity
{
    [Table("tb_schools", Schema = "public")]
    public class TbSchools
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]   // generated by the app (sch2026001)
        [Column("school_id")]
        [StringLength(100)]
        public string SchoolId { get; set; } = null!;

        [Column("school_code")][StringLength(100)] public string SchoolCode { get; set; } = null!;
        [Column("school_name")][StringLength(250)] public string SchoolName { get; set; } = null!;
        [Column("school_short_name")][StringLength(100)] public string? SchoolShortName { get; set; }

        [Column("school_type_id")] public long? SchoolTypeId { get; set; }
        [Column("school_level_id")] public long? SchoolLevelId { get; set; }
        [Column("board_type_id")] public long? BoardTypeId { get; set; }
        [Column("school_establish_year")] public short? SchoolEstablishYear { get; set; }

        [Column("school_gstin")][StringLength(15)] public string? SchoolGstin { get; set; }
        [Column("school_pan")][StringLength(10)] public string? SchoolPan { get; set; }

        [Column("country_id")] public int? CountryId { get; set; }
        [Column("state_id")] public int? StateId { get; set; }
        [Column("district_id")] public int? DistrictId { get; set; }
        [Column("city_id")] public int? CityId { get; set; }

        [Column("address_line1")][StringLength(250)] public string? AddressLine1 { get; set; }
        [Column("address_line2")][StringLength(250)] public string? AddressLine2 { get; set; }
        [Column("pincode")][StringLength(20)] public string? Pincode { get; set; }

        [Column("email")][StringLength(150)] public string? Email { get; set; }
        [Column("mobile_number")][StringLength(20)] public string? MobileNumber { get; set; }
        [Column("website")][StringLength(200)] public string? Website { get; set; }

        [Column("logo_url")] public string? LogoUrl { get; set; }

        [Column("subscription_plan_id")] public long? SubscriptionPlanId { get; set; }
        [Column("subscription_start_date")] public DateOnly? SubscriptionStartDate { get; set; }
        [Column("subscription_end_date")] public DateOnly? SubscriptionEndDate { get; set; }
        [Column("subscription_status_id")] public int? SubscriptionStatusId { get; set; }

        [Column("school_status_id")] public int? SchoolStatusId { get; set; }

        [Column("created_at")] public DateTime CreatedAt { get; set; }
        [Column("updated_at")] public DateTime UpdatedAt { get; set; }

        public ICollection<TbSchoolContacts> Contacts { get; set; } = new List<TbSchoolContacts>();
    }
}